export const commonJobTitles = [
  // Product
  "Product Manager",
  "Senior Product Manager",
  "Principal Product Manager",
  "VP of Product",
  "Chief Product Officer",
  "Product Owner",
  "Technical Product Manager",
  "Associate Product Manager",
  "Group Product Manager",
  
  // Engineering
  "Software Engineer",
  "Senior Software Engineer",
  "Staff Engineer",
  "Principal Engineer",
  "Engineering Manager",
  "Director of Engineering",
  "VP of Engineering",
  "CTO",
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Platform Engineer",
  "Security Engineer",
  "Mobile Developer",
  "iOS Developer",
  "Android Developer",
  "Embedded Systems Engineer",
  "Solutions Architect",
  "Technical Architect",
  
  // Data
  "Data Analyst",
  "Senior Data Analyst",
  "Data Scientist",
  "Senior Data Scientist",
  "Machine Learning Engineer",
  "AI Research Scientist",
  "Data Engineer",
  "Analytics Manager",
  "Head of Data",
  "Business Intelligence Analyst",
  "Data Architect",
  
  // Design
  "Product Designer",
  "Senior Product Designer",
  "UX Designer",
  "UI Designer",
  "UX Researcher",
  "Design Manager",
  "Head of Design",
  "Creative Director",
  "Visual Designer",
  "Interaction Designer",
  "UX Writer",
  "Design Systems Designer",
  
  // Marketing
  "Marketing Manager",
  "Growth Marketing Manager",
  "Product Marketing Manager",
  "Content Marketing Manager",
  "Performance Marketing Manager",
  "Head of Marketing",
  "CMO",
  "Digital Marketing Manager",
  "SEO Specialist",
  "Brand Manager",
  "Social Media Manager",
  
  // Sales
  "Account Executive",
  "Sales Development Representative",
  "Business Development Representative",
  "Sales Manager",
  "Head of Sales",
  "VP of Sales",
  "Customer Success Manager",
  "Account Manager",
  "Sales Engineer",
  "Enterprise Account Executive",
  
  // Operations
  "Operations Manager",
  "Program Manager",
  "Project Manager",
  "Chief Operating Officer",
  "Business Operations Analyst",
  "Technical Program Manager",
  "Scrum Master",
  "Agile Coach",
  
  // Finance
  "Financial Analyst",
  "Accountant",
  "Finance Manager",
  "CFO",
  "Controller",
  "FP&A Analyst",
  "Investment Analyst",
  
  // People/HR
  "Recruiter",
  "Technical Recruiter",
  "HR Manager",
  "Head of People",
  "Chief People Officer",
  "Talent Acquisition Manager",
  "People Operations Manager",
  "Compensation Analyst",
  
  // Customer Experience
  "Customer Support Manager",
  "Customer Experience Manager",
  "Support Engineer",
  "Community Manager",
  "Customer Support Specialist",
  "Technical Support Engineer",
  
  // Strategy & Consulting
  "Strategy Consultant",
  "Management Consultant",
  "Business Analyst",
  "Chief Strategy Officer",
  
  // Legal & Compliance
  "Legal Counsel",
  "Compliance Manager",
  "Privacy Officer",
  "Paralegal",
].sort();
